### ISSUE TITLE
[EPIC] Gift Cards

### ISSUE THREAD

**Issue by r0wdy1** [zkBob/zkbob-client-js#77]
## What to do?

- [x] (WIP) Create generating of gift cards + Make a change to the lib -> https://github.com/zkBob/zkbob-console/issues/44
- [x] (PR) Delegated prover -> https://github.com/zkBob/zkbob-prover/issues/1
- [x] UI changes -> https://github.com/zkBob/zkbob-ui/issues/120
- [x] UI redemption flow -> https://github.com/zkBob/zkbob-ui/issues/122
- [x] UI delegated prover  -> https://github.com/zkBob/zkbob-ui/issues/123

**Comment by maikReal** [comment]
@r0wdy1 add some fix for Gift Cards
